environment: 'development'

nashville:
  http:
    host: 'localhost'
    port: 3000

gallatin:
  database:
    type: 'postgres'
    host: 'localhost'
    port: 5432
    user: 'root'
    password: 'root'
    database: 'root'

