version: '3'
services:
  nashville:
    build: ./nashville
    ports:
      - 3000:3000
    volumes:
      - ./nashville:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  gallatin:
    build: ./gallatin
    ports:
      - 3001:3001
    volumes:
      - ./gallatin:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - 5432:5432
