version: '3'
services:
  nashville:
    build: ./apps/nashville
    ports:
      - "3000:3000"
    volumes:
      - ./apps/nashville:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - gallatin

  gallatin:
    build: ./apps/gallatin
    ports:
      - "3001:3001"
    volumes:
      - ./apps/gallatin:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
